#Test file to check if the globals are properly defined and
#if the same output is resulted, no matter of the compiler
#machine arichtecture is used.


LET glb0 AS BOOL;
LET glb1 AS UINT;
LET glb2 AS DATE;
LET glb3 AS DATETIME;
LET glb4 AS HIRESTIME;
LET glb5 AS INT8;
LET glb6 AS INT16;
LET glb7 AS INT32;
LET glb8 AS INT64;
LET glb9 AS UINT8;
LET glb10 AS UINT16;
LET glb11 AS UINT32;
LET glb12 AS UINT64;
LET glb13 AS REAL;
LET glb14 AS RICHREAL;
LET glb15 AS TEXT;

LET glb16 AS ARRAY OF BOOL;
LET glb17 AS ARRAY OF UINT;
LET glb18 AS ARRAY OF DATE;
LET glb19 AS ARRAY OF DATETIME;
LET glb20 AS ARRAY OF HIRESTIME;
LET glb21 AS ARRAY OF INT8;
LET glb22 AS ARRAY OF INT16;
LET glb23 AS ARRAY OF INT32;
LET glb24 AS ARRAY OF INT64;
LET glb25 AS ARRAY OF UINT8;
LET glb26 AS ARRAY OF UINT16;
LET glb27 AS ARRAY OF UINT32;
LET glb28 AS ARRAY OF UINT64;
LET glb29 AS ARRAY OF REAL;
LET glb30 AS ARRAY OF RICHREAL;

LET glb31 AS FIELD OF BOOL;
LET glb32 AS FIELD OF UINT;
LET glb33 AS FIELD OF DATE;
LET glb34 AS FIELD OF DATETIME;
LET glb35 AS FIELD OF HIRESTIME;
LET glb36 AS FIELD OF INT8;
LET glb37 AS FIELD OF INT16;
LET glb38 AS FIELD OF INT32;
LET glb39 AS FIELD OF INT64;
LET glb40 AS FIELD OF UINT8;
LET glb41 AS FIELD OF UINT16;
LET glb42 AS FIELD OF UINT32;
LET glb43 AS FIELD OF UINT64;
LET glb44 AS FIELD OF REAL;
LET glb45 AS FIELD OF RICHREAL;
LET glb46 AS FIELD OF TEXT;

LET glb47 AS FIELD OF ARRAY OF BOOL;
LET glb48 AS FIELD OF ARRAY OF UINT;
LET glb49 AS FIELD OF ARRAY OF DATE;
LET glb65 AS FIELD OF ARRAY OF DATETIME;
LET glb51 AS FIELD OF ARRAY OF HIRESTIME;
LET glb52 AS FIELD OF ARRAY OF INT8;
LET glb53 AS FIELD OF ARRAY OF INT16;
LET glb54 AS FIELD OF ARRAY OF INT32;
LET glb55 AS FIELD OF ARRAY OF INT64;
LET glb56 AS FIELD OF ARRAY OF UINT8;
LET glb57 AS FIELD OF ARRAY OF UINT16;
LET glb58 AS FIELD OF ARRAY OF UINT32;
LET glb59 AS FIELD OF ARRAY OF UINT64;
LET glb60 AS FIELD OF ARRAY OF REAL;
LET glb61 AS FIELD OF ARRAY OF RICHREAL;

LET glg65 AS TABLE OF (field1 AS DATE, field2 AS ARRAY OF RICHREAL, field3 AS TEXT);

EXTERN LET glbex1 AS FIELD OF ARRAY OF REAL;
EXTERN LET glbex2 AS FIELD OF ARRAY OF RICHREAL;


PROCEDURE external_activator (p1 AS ARRAY, p2 as FIELD, p3 AS TABLE) return FIELD
DO
	glbex1 = NULL;
	glbex2 = NULL;

	p1 = NULL;
	p2 = NULL;
	p3 = NULL;

	RETURN NULL;
ENDPROC

