#Test file to check if the globals are properly defined and
#if the same output is resulted, no matter of the compiler
#machine arichtecture is used.


VAR glb0 BOOL;
VAR glb1 UINT;
VAR glb2 DATE;
VAR glb3 DATETIME;
VAR glb4 HIRESTIME;
VAR glb5 INT8;
VAR glb6 INT16;
VAR glb7 INT32;
VAR glb8 INT64;
VAR glb9 UINT8;
VAR glb10 UINT16;
VAR glb11 UINT32;
VAR glb12 UINT64;
VAR glb13 REAL;
VAR glb14 RICHREAL;
VAR glb15 TEXT;

VAR glb16 BOOL ARRAY;
VAR glb17 UINT ARRAY;
VAR glb18 DATE ARRAY;
VAR glb19 DATETIME ARRAY;
VAR glb20 HIRESTIME ARRAY;
VAR glb21 INT8 ARRAY;
VAR glb22 INT16 ARRAY;
VAR glb23 INT32 ARRAY;
VAR glb24 INT64 ARRAY;
VAR glb25 UINT8 ARRAY;
VAR glb26 UINT16 ARRAY;
VAR glb27 UINT32 ARRAY;
VAR glb28 UINT64 ARRAY;
VAR glb29 REAL ARRAY;
VAR glb30 RICHREAL ARRAY;

VAR glb31 BOOL FIELD;
VAR glb32 UINT FIELD;
VAR glb33 DATE FIELD;
VAR glb34 DATETIME FIELD;
VAR glb35 HIRESTIME FIELD;
VAR glb36 INT8 FIELD;
VAR glb37 INT16 FIELD;
VAR glb38 INT32 FIELD;
VAR glb39 INT64 FIELD;
VAR glb40 UINT8 FIELD;
VAR glb41 UINT16 FIELD;
VAR glb42 UINT32 FIELD;
VAR glb43 UINT64 FIELD;
VAR glb44 REAL FIELD;
VAR glb45 RICHREAL FIELD;
VAR glb46 TEXT FIELD;

VAR glb47 BOOL ARRAY FIELD;
VAR glb48 UINT ARRAY FIELD;
VAR glb49 DATE ARRAY FIELD;
VAR glb65 DATETIME ARRAY FIELD;
VAR glb51 HIRESTIME ARRAY FIELD;
VAR glb52 INT8 ARRAY FIELD;
VAR glb53 INT16 ARRAY FIELD;
VAR glb54 INT32 ARRAY FIELD;
VAR glb55 INT64 ARRAY FIELD;
VAR glb56 UINT8 ARRAY FIELD;
VAR glb57 UINT16 ARRAY FIELD;
VAR glb58 UINT32 ARRAY FIELD;
VAR glb59 UINT64 ARRAY FIELD;
VAR glb60 REAL ARRAY FIELD;
VAR glb61 RICHREAL ARRAY FIELD;

VAR glg65 TABLE OF (field1 DATE, field2 RICHREAL ARRAY, field3 TEXT);

EXTERN VAR glbex1 REAL ARRAY FIELD;
EXTERN VAR glbex2 RICHREAL ARRAY FIELD;


PROCEDURE external_activator (p1 ARRAY, p2 as FIELD, p3 TABLE) return FIELD
DO
	glbex1 = NULL;
	glbex2 = NULL;

	p1 = NULL;
	p2 = NULL;
	p3 = NULL;

	RETURN NULL;
ENDPROC

