#Test file to check if the globals are properly defined and
#if the same output is resulted, no matter of the compiler
#machine arichtecture is used.


VAR glb0 AS BOOL;
VAR glb1 AS UINT;
VAR glb2 AS DATE;
VAR glb3 AS DATETIME;
VAR glb4 AS HIRESTIME;
VAR glb5 AS INT8;
VAR glb6 AS INT16;
VAR glb7 AS INT32;
VAR glb8 AS INT64;
VAR glb9 AS UINT8;
VAR glb10 AS UINT16;
VAR glb11 AS UINT32;
VAR glb12 AS UINT64;
VAR glb13 AS REAL;
VAR glb14 AS RICHREAL;
VAR glb15 AS TEXT;

VAR glb16 AS ARRAY OF BOOL;
VAR glb17 AS ARRAY OF UINT;
VAR glb18 AS ARRAY OF DATE;
VAR glb19 AS ARRAY OF DATETIME;
VAR glb20 AS ARRAY OF HIRESTIME;
VAR glb21 AS ARRAY OF INT8;
VAR glb22 AS ARRAY OF INT16;
VAR glb23 AS ARRAY OF INT32;
VAR glb24 AS ARRAY OF INT64;
VAR glb25 AS ARRAY OF UINT8;
VAR glb26 AS ARRAY OF UINT16;
VAR glb27 AS ARRAY OF UINT32;
VAR glb28 AS ARRAY OF UINT64;
VAR glb29 AS ARRAY OF REAL;
VAR glb30 AS ARRAY OF RICHREAL;

VAR glb31 AS FIELD OF BOOL;
VAR glb32 AS FIELD OF UINT;
VAR glb33 AS FIELD OF DATE;
VAR glb34 AS FIELD OF DATETIME;
VAR glb35 AS FIELD OF HIRESTIME;
VAR glb36 AS FIELD OF INT8;
VAR glb37 AS FIELD OF INT16;
VAR glb38 AS FIELD OF INT32;
VAR glb39 AS FIELD OF INT64;
VAR glb40 AS FIELD OF UINT8;
VAR glb41 AS FIELD OF UINT16;
VAR glb42 AS FIELD OF UINT32;
VAR glb43 AS FIELD OF UINT64;
VAR glb44 AS FIELD OF REAL;
VAR glb45 AS FIELD OF RICHREAL;
VAR glb46 AS FIELD OF TEXT;

VAR glb47 AS FIELD OF ARRAY OF BOOL;
VAR glb48 AS FIELD OF ARRAY OF UINT;
VAR glb49 AS FIELD OF ARRAY OF DATE;
VAR glb65 AS FIELD OF ARRAY OF DATETIME;
VAR glb51 AS FIELD OF ARRAY OF HIRESTIME;
VAR glb52 AS FIELD OF ARRAY OF INT8;
VAR glb53 AS FIELD OF ARRAY OF INT16;
VAR glb54 AS FIELD OF ARRAY OF INT32;
VAR glb55 AS FIELD OF ARRAY OF INT64;
VAR glb56 AS FIELD OF ARRAY OF UINT8;
VAR glb57 AS FIELD OF ARRAY OF UINT16;
VAR glb58 AS FIELD OF ARRAY OF UINT32;
VAR glb59 AS FIELD OF ARRAY OF UINT64;
VAR glb60 AS FIELD OF ARRAY OF REAL;
VAR glb61 AS FIELD OF ARRAY OF RICHREAL;

VAR glg65 AS TABLE OF (field1 AS DATE, field2 AS ARRAY OF RICHREAL, field3 AS TEXT);

EXTERN VAR glbex1 AS FIELD OF ARRAY OF REAL;
EXTERN VAR glbex2 AS FIELD OF ARRAY OF RICHREAL;


PROCEDURE external_activator (p1 AS ARRAY, p2 as FIELD, p3 AS TABLE) return FIELD
DO
	glbex1 = NULL;
	glbex2 = NULL;

	p1 = NULL;
	p2 = NULL;
	p3 = NULL;

	RETURN NULL;
ENDPROC

