################################################################################
# Test module used to verify the handling of global variable description.
# 
# Iulian Popa
#
# Notes:
#  1. It contains a lot of global varibles (with long names) to make sure one
#     uses more than one comm frame to list them.
#  2. Same things for table feilds. It should facilitate the usage of multiple
#     comm frames for a full description.
################################################################################

LET bool_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS BOOL;
LET char_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS CHAR;
LET date_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS DATE;
LET datetime_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS DATETIME;
LET hirestime_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS HIRESTIME;
LET int8_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS INT8;
LET int16_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS INT16;
LET int32_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS INT32;
LET int64_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS INT64;
LET uint8_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS UINT8;
LET uint16_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS UINT16;
LET uint32_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS UINT32;
LET uint64_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS UINT64;
LET real_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS REAL;
LET richreal_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS RICHREAL;
LET text_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS TEXT;

LET array_bool_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS ARRAY OF BOOL;
LET array_char_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS ARRAY OF CHAR;
LET array_date_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS ARRAY OF DATE;
LET array_datetime_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS ARRAY OF DATETIME;
LET array_hirestime_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS ARRAY OF HIRESTIME;
LET array_int8_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS ARRAY OF INT8;
LET array_int16_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS ARRAY OF INT16;
LET array_int32_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS ARRAY OF INT32;
LET array_int64_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS ARRAY OF INT64;
LET array_uint8_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS ARRAY OF UINT8;
LET array_uint16_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS ARRAY OF UINT16;
LET array_uint32_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS ARRAY OF UINT32;
LET array_uint64_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS ARRAY OF UINT64;
LET array_real_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS ARRAY OF REAL;
LET array_richreal_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS ARRAY OF RICHREAL;
#LET array_text_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS ARRAY OF TEXT;

LET field_bool_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS FIELD OF BOOL;
LET field_char_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS FIELD OF CHAR;
LET field_date_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS FIELD OF DATE;
LET field_datetime_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS FIELD OF DATETIME;
LET field_hirestime_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS FIELD OF HIRESTIME;
LET field_int8_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS FIELD OF INT8;
LET field_int16_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS FIELD OF INT16;
LET field_int32_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS FIELD OF INT32;
LET field_int64_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS FIELD OF INT64;
LET field_uint8_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS FIELD OF UINT8;
LET field_uint16_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS FIELD OF UINT16;
LET field_uint32_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS FIELD OF UINT32;
LET field_uint64_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS FIELD OF UINT64;
LET field_real_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS FIELD OF REAL;
LET field_richreal_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS FIELD OF RICHREAL;
LET field_text_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS FIELD OF TEXT;

LET field_array_bool_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS FIELD OF ARRAY OF BOOL;
LET field_array_char_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS FIELD OF ARRAY OF CHAR;
LET field_array_date_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS FIELD OF ARRAY OF DATE;
LET field_array_datetime_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS FIELD OF ARRAY OF DATETIME;
LET field_array_hirestime_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS FIELD OF ARRAY OF HIRESTIME;
LET field_array_int8_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS FIELD OF ARRAY OF INT8;
LET field_array_int16_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS FIELD OF ARRAY OF INT16;
LET field_array_int32_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS FIELD OF ARRAY OF INT32;
LET field_array_int64_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS FIELD OF ARRAY OF INT64;
LET field_array_uint8_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS FIELD OF ARRAY OF UINT8;
LET field_array_uint16_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS FIELD OF ARRAY OF UINT16;
LET field_array_uint32_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS FIELD OF ARRAY OF UINT32;
LET field_array_uint64_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS FIELD OF ARRAY OF UINT64;
LET field_array_real_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS FIELD OF ARRAY OF REAL;
LET field_array_richreal_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS FIELD OF ARRAY OF RICHREAL;
#LET field_array_text_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS FIELD OF ARRAY OF TEXT;

LET one_field_table_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS TABLE OF (field1 AS BOOL);
LET complete_field_table_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS TABLE OF (
					bool_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad AS BOOL,
					char_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad AS CHAR,
					date_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad AS DATE,
					datetime_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad AS DATETIME,
					hirestime_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad AS HIRESTIME,
					int8_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad AS INT8,
					int16_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad AS INT16,
					int32_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad AS INT32,
					int64_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad AS INT64,
					uint8_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad AS UINT8,
					uint16_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad AS UINT16,
					uint32_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad AS UINT32,
					uint64_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad AS UINT64,
					real_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad AS REAL,
					richreal_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad AS RICHREAL,
					text_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad AS TEXT,

					array_bool_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad AS ARRAY OF BOOL,
					array_char_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad AS ARRAY OF CHAR,
					array_date_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad AS ARRAY OF DATE,
					array_datetime_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad AS ARRAY OF DATETIME,
					array_hirestime_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad AS ARRAY OF HIRESTIME,
					array_int8_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad AS ARRAY OF INT8,
					array_int16_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad AS ARRAY OF INT16,
					array_int32_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad AS ARRAY OF INT32,
					array_int64_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad AS ARRAY OF INT64,
					array_uint8_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad AS ARRAY OF UINT8,
					array_uint16_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad AS ARRAY OF UINT16,
					array_uint32_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad AS ARRAY OF UINT32,
					array_uint64_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad AS ARRAY OF UINT64,
					array_real_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad AS ARRAY OF REAL,
					array_richreal_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad AS ARRAY OF RICHREAL);
#					array_text_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad AS ARRAY OF TEXT);

