################################################################################
# Test module used to verify the handling of global variable description.
# 
# Iulian Popa
#
# Notes:
#  1. It contains a lot of global varibles (with long names) to make sure one
#     uses more than one comm frame to list them.
#  2. Same things for table feilds. It should facilitate the usage of multiple
#     comm frames for a full description.
################################################################################

VAR bool_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS BOOL;
VAR char_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS CHAR;
VAR date_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS DATE;
VAR datetime_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS DATETIME;
VAR hirestime_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS HIRESTIME;
VAR int8_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS INT8;
VAR int16_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS INT16;
VAR int32_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS INT32;
VAR int64_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS INT64;
VAR uint8_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS UINT8;
VAR uint16_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS UINT16;
VAR uint32_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS UINT32;
VAR uint64_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS UINT64;
VAR real_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS REAL;
VAR richreal_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS RICHREAL;
VAR text_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS TEXT;

VAR array_bool_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS ARRAY OF BOOL;
VAR array_char_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS ARRAY OF CHAR;
VAR array_date_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS ARRAY OF DATE;
VAR array_datetime_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS ARRAY OF DATETIME;
VAR array_hirestime_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS ARRAY OF HIRESTIME;
VAR array_int8_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS ARRAY OF INT8;
VAR array_int16_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS ARRAY OF INT16;
VAR array_int32_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS ARRAY OF INT32;
VAR array_int64_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS ARRAY OF INT64;
VAR array_uint8_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS ARRAY OF UINT8;
VAR array_uint16_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS ARRAY OF UINT16;
VAR array_uint32_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS ARRAY OF UINT32;
VAR array_uint64_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS ARRAY OF UINT64;
VAR array_real_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS ARRAY OF REAL;
VAR array_richreal_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS ARRAY OF RICHREAL;
#VAR array_text_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS ARRAY OF TEXT;

VAR field_bool_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS FIELD OF BOOL;
VAR field_char_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS FIELD OF CHAR;
VAR field_date_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS FIELD OF DATE;
VAR field_datetime_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS FIELD OF DATETIME;
VAR field_hirestime_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS FIELD OF HIRESTIME;
VAR field_int8_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS FIELD OF INT8;
VAR field_int16_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS FIELD OF INT16;
VAR field_int32_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS FIELD OF INT32;
VAR field_int64_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS FIELD OF INT64;
VAR field_uint8_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS FIELD OF UINT8;
VAR field_uint16_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS FIELD OF UINT16;
VAR field_uint32_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS FIELD OF UINT32;
VAR field_uint64_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS FIELD OF UINT64;
VAR field_real_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS FIELD OF REAL;
VAR field_richreal_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS FIELD OF RICHREAL;
VAR field_text_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS FIELD OF TEXT;

VAR field_array_bool_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS FIELD OF ARRAY OF BOOL;
VAR field_array_char_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS FIELD OF ARRAY OF CHAR;
VAR field_array_date_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS FIELD OF ARRAY OF DATE;
VAR field_array_datetime_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS FIELD OF ARRAY OF DATETIME;
VAR field_array_hirestime_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS FIELD OF ARRAY OF HIRESTIME;
VAR field_array_int8_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS FIELD OF ARRAY OF INT8;
VAR field_array_int16_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS FIELD OF ARRAY OF INT16;
VAR field_array_int32_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS FIELD OF ARRAY OF INT32;
VAR field_array_int64_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS FIELD OF ARRAY OF INT64;
VAR field_array_uint8_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS FIELD OF ARRAY OF UINT8;
VAR field_array_uint16_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS FIELD OF ARRAY OF UINT16;
VAR field_array_uint32_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS FIELD OF ARRAY OF UINT32;
VAR field_array_uint64_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS FIELD OF ARRAY OF UINT64;
VAR field_array_real_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS FIELD OF ARRAY OF REAL;
VAR field_array_richreal_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS FIELD OF ARRAY OF RICHREAL;
#VAR field_array_text_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS FIELD OF ARRAY OF TEXT;

VAR one_field_table_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS TABLE OF (field1 AS BOOL);
VAR complete_field_table_global_var_this_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good AS TABLE OF (
					bool_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad AS BOOL,
					char_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad AS CHAR,
					date_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad AS DATE,
					datetime_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad AS DATETIME,
					hirestime_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad AS HIRESTIME,
					int8_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad AS INT8,
					int16_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad AS INT16,
					int32_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad AS INT32,
					int64_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad AS INT64,
					uint8_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad AS UINT8,
					uint16_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad AS UINT16,
					uint32_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad AS UINT32,
					uint64_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad AS UINT64,
					real_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad AS REAL,
					richreal_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad AS RICHREAL,
					text_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad AS TEXT,

					array_bool_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad AS ARRAY OF BOOL,
					array_char_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad AS ARRAY OF CHAR,
					array_date_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad AS ARRAY OF DATE,
					array_datetime_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad AS ARRAY OF DATETIME,
					array_hirestime_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad AS ARRAY OF HIRESTIME,
					array_int8_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad AS ARRAY OF INT8,
					array_int16_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad AS ARRAY OF INT16,
					array_int32_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad AS ARRAY OF INT32,
					array_int64_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad AS ARRAY OF INT64,
					array_uint8_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad AS ARRAY OF UINT8,
					array_uint16_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad AS ARRAY OF UINT16,
					array_uint32_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad AS ARRAY OF UINT32,
					array_uint64_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad AS ARRAY OF UINT64,
					array_real_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad AS ARRAY OF REAL,
					array_richreal_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad AS ARRAY OF RICHREAL);
#					array_text_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad AS ARRAY OF TEXT);

