################################################################################
# Test module used to verify the handling of global variable description.
# 
# Iulian Popa
#
# Notes:
#  1. It contains a lot of procedures with long names to make sure one uses
#     more than one comm frame to list them.
#  2. Same things for table fields. It should facilitate the usage of multiple
#     comm frames for a full description.
################################################################################


PROCEDURE bool_return_proc_no_args_This_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good () RETURN BOOL
DO RETURN NULL; ENDPROC

PROCEDURE char_return_proc_no_args_This_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good () RETURN CHAR
DO RETURN NULL; ENDPROC

PROCEDURE date_return_proc_no_args_This_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good () RETURN DATE
DO RETURN NULL; ENDPROC

PROCEDURE datetime_return_proc_no_args_This_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good () RETURN DATETIME
DO RETURN NULL; ENDPROC

PROCEDURE hirestime_return_proc_no_args_This_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good () RETURN HIRESTIME
DO RETURN NULL; ENDPROC

PROCEDURE int8_return_proc_no_args_This_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good () RETURN INT8
DO RETURN NULL; ENDPROC

PROCEDURE int16_return_proc_no_args_This_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good () RETURN INT16
DO RETURN NULL; ENDPROC

PROCEDURE int32_return_proc_no_args_This_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good () RETURN INT32
DO RETURN NULL; ENDPROC

PROCEDURE int64_return_proc_no_args_This_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good () RETURN INT64
DO RETURN NULL; ENDPROC

PROCEDURE uint8_return_proc_no_args_This_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good () RETURN UINT8
DO RETURN NULL; ENDPROC

PROCEDURE uint16_return_proc_no_args_This_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good () RETURN UINT16
DO RETURN NULL; ENDPROC

PROCEDURE uint32_return_proc_no_args_This_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good () RETURN UINT32
DO RETURN NULL; ENDPROC

PROCEDURE uint64_return_proc_no_args_This_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good () RETURN UINT64
DO RETURN NULL; ENDPROC

PROCEDURE real_return_proc_no_args_This_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good () RETURN REAL
DO RETURN NULL; ENDPROC

PROCEDURE richreal_return_proc_no_args_This_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good () RETURN RICHREAL
DO RETURN NULL; ENDPROC

PROCEDURE text_return_proc_no_args_This_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good () RETURN TEXT
DO RETURN NULL; ENDPROC


#
# Array returned values part.
#

PROCEDURE array_bool_return_proc_no_args_This_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good () RETURN  BOOL ARRAY
DO RETURN NULL; ENDPROC

PROCEDURE array_char_return_proc_no_args_This_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good () RETURN  CHAR ARRAY
DO RETURN NULL; ENDPROC

PROCEDURE array_date_return_proc_no_args_This_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good () RETURN  DATE ARRAY
DO RETURN NULL; ENDPROC

PROCEDURE array_datetime_return_proc_no_args_This_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good () RETURN  DATETIME ARRAY
DO RETURN NULL; ENDPROC

PROCEDURE array_hirestime_return_proc_no_args_This_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good () RETURN  HIRESTIME ARRAY
DO RETURN NULL; ENDPROC

PROCEDURE array_int8_return_proc_no_args_This_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good () RETURN  INT8 ARRAY
DO RETURN NULL; ENDPROC

PROCEDURE array_int16_return_proc_no_args_This_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good () RETURN  INT16 ARRAY
DO RETURN NULL; ENDPROC

PROCEDURE array_int32_return_proc_no_args_This_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good () RETURN  INT32 ARRAY
DO RETURN NULL; ENDPROC

PROCEDURE array_int64_return_proc_no_args_This_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good () RETURN  INT64 ARRAY
DO RETURN NULL; ENDPROC

PROCEDURE array_uint8_return_proc_no_args_This_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good () RETURN  UINT8 ARRAY
DO RETURN NULL; ENDPROC

PROCEDURE array_uint16_return_proc_no_args_This_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good () RETURN  UINT16 ARRAY
DO RETURN NULL; ENDPROC

PROCEDURE array_uint32_return_proc_no_args_This_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good () RETURN  UINT32 ARRAY
DO RETURN NULL; ENDPROC

PROCEDURE array_uint64_return_proc_no_args_This_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good () RETURN  UINT64 ARRAY
DO RETURN NULL; ENDPROC

PROCEDURE array_real_return_proc_no_args_This_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good () RETURN  REAL ARRAY
DO RETURN NULL; ENDPROC

PROCEDURE array_richreal_return_proc_no_args_This_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good () RETURN  RICHREAL ARRAY
DO RETURN NULL; ENDPROC

#PROCEDURE array_text_return_proc_no_args_This_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good () RETURN  TEXT ARRAY
#DO RETURN NULL; ENDPROC

PROCEDURE array_return_proc_no_args_This_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good () RETURN ARRAY 
DO RETURN NULL; ENDPROC

#
# Field returned values part.
#

PROCEDURE field_bool_return_proc_no_args_This_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good () RETURN  BOOL FIELD
DO RETURN NULL; ENDPROC

PROCEDURE field_char_return_proc_no_args_This_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good () RETURN  CHAR FIELD
DO RETURN NULL; ENDPROC

PROCEDURE field_date_return_proc_no_args_This_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good () RETURN  DATE FIELD
DO RETURN NULL; ENDPROC

PROCEDURE field_datetime_return_proc_no_args_This_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good () RETURN  DATETIME FIELD
DO RETURN NULL; ENDPROC

PROCEDURE field_hirestime_return_proc_no_args_This_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good () RETURN  HIRESTIME FIELD
DO RETURN NULL; ENDPROC

PROCEDURE field_int8_return_proc_no_args_This_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good () RETURN  INT8 FIELD
DO RETURN NULL; ENDPROC

PROCEDURE field_int16_return_proc_no_args_This_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good () RETURN  INT16 FIELD
DO RETURN NULL; ENDPROC

PROCEDURE field_int32_return_proc_no_args_This_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good () RETURN  INT32 FIELD
DO RETURN NULL; ENDPROC

PROCEDURE field_int64_return_proc_no_args_This_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good () RETURN  INT64 FIELD
DO RETURN NULL; ENDPROC

PROCEDURE field_uint8_return_proc_no_args_This_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good () RETURN  UINT8 FIELD
DO RETURN NULL; ENDPROC

PROCEDURE field_uint16_return_proc_no_args_This_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good () RETURN  UINT16 FIELD
DO RETURN NULL; ENDPROC

PROCEDURE field_uint32_return_proc_no_args_This_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good () RETURN  UINT32 FIELD
DO RETURN NULL; ENDPROC

PROCEDURE field_uint64_return_proc_no_args_This_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good () RETURN  UINT64 FIELD
DO RETURN NULL; ENDPROC

PROCEDURE field_real_return_proc_no_args_This_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good () RETURN  REAL FIELD
DO RETURN NULL; ENDPROC

PROCEDURE field_richreal_return_proc_no_args_This_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good () RETURN  RICHREAL FIELD
DO RETURN NULL; ENDPROC

PROCEDURE field_text_return_proc_no_args_This_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good () RETURN  TEXT FIELD
DO RETURN NULL; ENDPROC

#
# Field array returned values part.
#

PROCEDURE field_array_bool_return_proc_no_args_This_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good () RETURN  BOOL  ARRAY FIELD
DO RETURN NULL; ENDPROC

PROCEDURE field_array_char_return_proc_no_args_This_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good () RETURN  CHAR  ARRAY FIELD
DO RETURN NULL; ENDPROC

PROCEDURE field_array_date_return_proc_no_args_This_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good () RETURN  DATE  ARRAY FIELD
DO RETURN NULL; ENDPROC

PROCEDURE field_array_datetime_return_proc_no_args_This_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good () RETURN  DATETIME  ARRAY FIELD
DO RETURN NULL; ENDPROC

PROCEDURE field_array_hirestime_return_proc_no_args_This_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good () RETURN  HIRESTIME  ARRAY FIELD
DO RETURN NULL; ENDPROC

PROCEDURE field_array_int8_return_proc_no_args_This_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good () RETURN  INT8  ARRAY FIELD
DO RETURN NULL; ENDPROC

PROCEDURE field_array_int16_return_proc_no_args_This_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good () RETURN  INT16  ARRAY FIELD
DO RETURN NULL; ENDPROC

PROCEDURE field_array_int32_return_proc_no_args_This_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good () RETURN  INT32  ARRAY FIELD
DO RETURN NULL; ENDPROC

PROCEDURE field_array_int64_return_proc_no_args_This_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good () RETURN  INT64  ARRAY FIELD
DO RETURN NULL; ENDPROC

PROCEDURE field_array_uint8_return_proc_no_args_This_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good () RETURN  UINT8  ARRAY FIELD
DO RETURN NULL; ENDPROC

PROCEDURE field_array_uint16_return_proc_no_args_This_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good () RETURN  UINT16  ARRAY FIELD
DO RETURN NULL; ENDPROC

PROCEDURE field_array_uint32_return_proc_no_args_This_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good () RETURN  UINT32  ARRAY FIELD
DO RETURN NULL; ENDPROC

PROCEDURE field_array_uint64_return_proc_no_args_This_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good () RETURN  UINT64  ARRAY FIELD
DO RETURN NULL; ENDPROC

PROCEDURE field_array_real_return_proc_no_args_This_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good () RETURN  REAL  ARRAY FIELD
DO RETURN NULL; ENDPROC

PROCEDURE field_array_richreal_return_proc_no_args_This_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good () RETURN  RICHREAL  ARRAY FIELD
DO RETURN NULL; ENDPROC

#PROCEDURE field_array_text_return_proc_no_args_This_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good () RETURN  TEXT  ARRAY FIELD
#DO RETURN NULL; ENDPROC

PROCEDURE field_array_return_proc_no_args_This_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good () RETURN  ARRAY FIELD 
DO RETURN NULL; ENDPROC

PROCEDURE field_return_proc_no_args_This_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good () RETURN FIELD 
DO RETURN NULL; ENDPROC

#
# Table returned values part.
#

PROCEDURE one_field_table_return_proc_no_args_This_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good () RETURN TABLE ( field1 TEXT) 
DO RETURN NULL; ENDPROC

PROCEDURE two_field_table_return_proc_no_args_This_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good () RETURN TABLE ( field1 CHAR, field2 UINT64 ARRAY) 
DO RETURN NULL; ENDPROC

PROCEDURE table_return_proc_no_args_This_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good () RETURN TABLE 
DO RETURN NULL; ENDPROC

#
# The complex procedure definition
#

PROCEDURE table_return_proc_all_type_args_This_is_a_long_variable_name_suffix_coz_I_need_to_trigger_an_odd_behavior_001_good (
	bool_arg BOOL,
	char_arg CHAR,
	date_arg DATE,
	datetime_arg DATETIME,
	hirestime_arg HIRESTIME,
	int8_arg INT8,
	int16_arg INT16,
	int32_arg INT32,
	int64_arg INT64,
	uint8_arg UINT8,
	uint16_arg UINT16,
	uint32_arg UINT32,
	uint64_arg UINT64,
	real_arg REAL,
	richreal_arg RICHREAL,
	text_arg TEXT,

	array_bool_arg BOOL ARRAY,
	array_char_arg CHAR ARRAY,
	array_date_arg DATE ARRAY,
	array_datetime_arg DATETIME ARRAY,
	array_hirestime_arg HIRESTIME ARRAY,
	array_int8_arg INT8 ARRAY,
	array_int16_arg INT16 ARRAY,
	array_int32_arg INT32 ARRAY,
	array_int64_arg INT64 ARRAY,
	array_uint8_arg UINT8 ARRAY,
	array_uint16_arg UINT16 ARRAY,
	array_uint32_arg UINT32 ARRAY,
	array_uint64_arg UINT64 ARRAY,
	array_real_arg REAL ARRAY,
	array_richreal_arg RICHREAL ARRAY,
#	array_text_arg TEXT ARRAY,
	array_arg ARRAY,

	field_bool_arg BOOL FIELD,
	field_char_arg CHAR FIELD,
	field_date_arg DATE FIELD,
	field_datetime_arg DATETIME FIELD,
	field_hirestime_arg HIRESTIME FIELD,
	field_int8_arg INT8 FIELD,
	field_int16_arg INT16 FIELD,
	field_int32_arg INT32 FIELD,
	field_int64_arg INT64 FIELD,
	field_uint8_arg UINT8 FIELD,
	field_uint16_arg UINT16 FIELD,
	field_uint32_arg UINT32 FIELD,
	field_uint64_arg UINT64 FIELD,
	field_real_arg REAL FIELD,
	field_richreal_arg RICHREAL FIELD,
	field_text_arg TEXT FIELD,

	field_array_bool_arg BOOL   ARRAY FIELD,
	field_array_char_arg CHAR   ARRAY FIELD,
	field_array_date_arg DATE   ARRAY FIELD,
	field_array_datetime_arg DATETIME   ARRAY FIELD,
	field_array_hirestime_arg HIRESTIME   ARRAY FIELD,
	field_array_int8_arg INT8   ARRAY FIELD,
	field_array_int16_arg INT16   ARRAY FIELD,
	field_array_int32_arg INT32   ARRAY FIELD,
	field_array_int64_arg INT64   ARRAY FIELD,
	field_array_uint8_arg UINT8   ARRAY FIELD,
	field_array_uint16_arg UINT16   ARRAY FIELD,
	field_array_uint32_arg UINT32   ARRAY FIELD,
	field_array_uint64_arg UINT64   ARRAY FIELD,
	field_array_real_arg REAL   ARRAY FIELD,
	field_array_richreal_arg RICHREAL   ARRAY FIELD,
#	field_array_text_arg TEXT   ARRAY FIELD,
	field_array_arg   ARRAY FIELD,
	field_arg FIELD,

	table_arg TABLE,
	table_complete_arg TABLE (
		bool_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad BOOL,
		char_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad CHAR,
		date_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad DATE,
		datetime_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad DATETIME,
		hirestime_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad HIRESTIME,
		int8_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad INT8,
		int16_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad INT16,
		int32_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad INT32,
		int64_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad INT64,
		uint8_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad UINT8,
		uint16_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad UINT16,
		uint32_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad UINT32,
		uint64_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad UINT64,
		real_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad REAL,
		richreal_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad RICHREAL,
		text_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad TEXT,

		array_bool_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad BOOL ARRAY,
		array_char_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad CHAR ARRAY,
		array_date_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad DATE ARRAY,
		array_datetime_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad DATETIME ARRAY,
		array_hirestime_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad HIRESTIME ARRAY,
		array_int8_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad INT8 ARRAY,
		array_int16_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad INT16 ARRAY,
		array_int32_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad INT32 ARRAY,
		array_int64_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad INT64 ARRAY,
		array_uint8_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad UINT8 ARRAY,
		array_uint16_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad UINT16 ARRAY,
		array_uint32_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad UINT32 ARRAY,
		array_uint64_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad UINT64 ARRAY,
		array_real_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad REAL ARRAY,
		array_richreal_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad RICHREAL ARRAY))
#		array_text_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad TEXT ARRAY))
RETURN TABLE (
		bool_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad BOOL,
		char_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad CHAR,
		date_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad DATE,
		datetime_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad DATETIME,
		hirestime_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad HIRESTIME,
		int8_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad INT8,
		int16_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad INT16,
		int32_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad INT32,
		int64_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad INT64,
		uint8_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad UINT8,
		uint16_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad UINT16,
		uint32_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad UINT32,
		uint64_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad UINT64,
		real_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad REAL,
		richreal_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad RICHREAL,
		text_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad TEXT,

		array_bool_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad BOOL ARRAY,
		array_char_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad CHAR ARRAY,
		array_date_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad DATE ARRAY,
		array_datetime_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad DATETIME ARRAY,
		array_hirestime_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad HIRESTIME ARRAY,
		array_int8_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad INT8 ARRAY,
		array_int16_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad INT16 ARRAY,
		array_int32_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad INT32 ARRAY,
		array_int64_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad INT64 ARRAY,
		array_uint8_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad UINT8 ARRAY,
		array_uint16_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad UINT16 ARRAY,
		array_uint32_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad UINT32 ARRAY,
		array_uint64_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad UINT64 ARRAY,
		array_real_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad REAL ARRAY,
		array_richreal_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad RICHREAL ARRAY)
#		array_text_field_This_is_a_long_field_suffix_coz_I_need_to_trigger_an_odd_behavior_002_bad TEXT ARRAY)
DO RETURN table_complete_arg; ENDPROC

